export const TYPES = {
    SINGLE: 'single',
    MULTI: 'multi'
}

export const DATA = [
    { label: 'Siddarth Patel' },
    { label: 'Sanchay Javeria'},
    { label: 'Mike Sadler' },
    { label: 'Ankit Tibrewal' },
    { label: 'Zach Kayyali' },
    { label: 'Sho Weimer' },
    { label: 'Mikela Dockery' },
    { label: 'Stephanny Cocconcelli' },
    { label: 'Siddarth' },
    { label: 'Sanchay'},
    { label: 'Mike' },
    { label: 'Ankit' },
    { label: 'Zach' },
    { label: 'Sho' },
    { label: 'Mikela' },
    { label: 'Stephanny' },
    { label: 'Patel' },
    { label: 'Javeria'},
    { label: 'Sadler' },
    { label: 'Tibrewal' },
    { label: 'Kayyali' },
    { label: 'Weimer' },
    { label: 'Dockery' },
    { label: 'Cocconcelli' },
    { label: 'Surfer' },
    { label: 'boarder'},
    { label: 'cool' },
    { label: 'meh' },
    { label: 'Oliver' },
    { label: 'jamie' },
    { label: 'yessir' },
    { label: 'mylife' },
    { label: 'North Carolina' },
    { label: 'South Carolina'},
    { label: 'Washington' },
    { label: 'California' },
    { label: 'Goergia' },
    { label: 'Florida' },
    { label: 'Indiana' },
    { label: 'New York' },
    { label: 'Patel rogan' },
    { label: 'Javeria rogan'},
    { label: 'Sadler rogan' },
    { label: 'Tibrewal rogan' },
    { label: 'Kayyali rogan' },
    { label: 'Weimer rogan' },
    { label: 'Dockery rogan' },
    { label: 'Cocconcelli rogan' },
    { label: 'Coleman Patel' },
    { label: 'Coleman Javeria'},
    { label: 'Coleman Sadler' },
    { label: 'Coleman Tibrewal' },
    { label: 'Coleman Kayyali' },
    { label: 'Coleman Weimer' },
    { label: 'Coleman Dockery' },
    { label: 'Coleman Cocconcelli' },
  ]